

    # must be unique in a given SonarQube instance
    sonar.projectKey=org.springframework.samples:spring-petclinic

    # this is the name displayed in the SonarQube UI
    sonar.projectName=custom
    sonar.projectVersion=1.0

    sonar.sources=.
    sonar.language=java

    sonar.inclusions=**/*.java
    sonar.exclusions=**/*Test*.java,**/jalo/**,**/gensrc/**
    sonar.java.binaries=**/classes/**

